[project]
name = "zguard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fastlorenzo", email = "git@bernardi.be" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "redis[standard]>=6.4.0",
]
